apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: <JOB_NAME>
spec:
  slotsPerWorker: 1
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: 763104351884.dkr.ecr.us-east-1.amazonaws.com/aws-samples-mxnet-training:1.8.0-gpu-py37-cu110-ubuntu16.04-example
            name: <JOB_NAME>
            args:
            - --epochs
            - "10"
            - --lr
            - "0.001"
            command:
            - mpirun
            - -mca
            - btl_tcp_if_exclude
            - lo
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - --bind-to
            - none
            - -map-by
            - slot
            - -x
            - LD_LIBRARY_PATH
            - -x
            - PATH
            - -x
            - NCCL_SOCKET_IFNAME=eth0
            - -x
            - NCCL_DEBUG=INFO
            - -x
            - MXNET_CUDNN_AUTOTUNE_DEFAULT=0
            - python
            - /horovod/examples/mxnet_mnist.py
    Worker:
      replicas: <NUM_WORKERS>
      template:
        spec:
          containers:
          - image: 763104351884.dkr.ecr.us-east-1.amazonaws.com/aws-samples-mxnet-training:1.8.0-gpu-py37-cu110-ubuntu16.04-example
            name: mpi-worker
            resources:
              limits:
                nvidia.com/gpu: <GPUS>

docker run -d --name kong-database   -p 5432:5432  -e "POSTGRES_USER=kong"  -e "POSTGRES_DB=kong"   postgres:9.6


docker run --rm   -e "KONG_DATABASE=postgres"  -e "KONG_PG_HOST=kong-database"  -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database"  kong:latest kong migrations bootstrap

docker run -d --name kong       -e "KONG_DATABASE=postgres"        -e "KONG_PG_HOST=kong-database"        -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database"        -e "KONG_PROXY_ACCESS_LOG=/dev/stdout"        -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout"        -e "KONG_PROXY_ERROR_LOG=/dev/stderr"        -e "KONG_ADMIN_ERROR_LOG=/dev/stderr"        -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl"        -p 8000:8000        -p 8443:8443        -p 8001:8001        -p 8444:8444        kong:latest

