apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-minio
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.250.10.61
    path: /home/xuwei/kubeflow/pv3
