apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minio-1
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/xuwei/kubeflow/pv3